preset: angular
plugins:
  # Analyze commits to determine release type
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        # Additional rules for version bumps
        - type: docs
          scope: README
          release: patch
        - type: perf
          release: patch
        - type: refactor
          scope: core
          release: patch
        # These don't trigger releases but appear in changelog
        - type: docs
          release: false
        - type: style
          release: false
        - type: test
          release: false
        - type: ci
          release: false
        - type: chore
          release: false

  # Generate release notes
  - - "@semantic-release/release-notes-generator"
    - preset: angular
      presetConfig:
        types:
          - type: feat
            section: "ðŸš€ Features"
          - type: fix
            section: "ðŸ› Bug Fixes"
          - type: docs
            section: "ðŸ“š Documentation"
          - type: style
            section: "ðŸ’„ Styles"
          - type: refactor
            section: "â™»ï¸ Code Refactoring"
          - type: perf
            section: "âš¡ Performance Improvements"
          - type: test
            section: "âœ… Tests"
          - type: build
            section: "ðŸ—ï¸ Build System"
          - type: ci
            section: "ðŸ‘· CI/CD"
          - type: chore
            section: "ðŸ”§ Chores"
            hidden: true  # Include in changelog but hide by default
  - "@semantic-release/github"
  # - "@semantic-release/changelog"
  # - "@semantic-release/git"
  # - - "@semantic-release/exec"
  #   - publishCmd: |
  #       echo "${nextRelease.notes}" > /tmp/release-notes.md
  #       goreleaser release --release-notes /tmp/release-notes.md --clean
