name: Bug Report
description: Report a problem in project
labels: 'bug'
body:

  - type: markdown
    attributes:
      value: |
        *Before reporting:*
        - Search [existing issues](https://github.com/Jacobus-afk/GCP-Tunneler/issues?q=is%3Aissue+is%3Aopen+label%3Abug) (including [closed](https://github.com/Jacobus-afk/GCP-Tunneler/issues?q=is%3Aissue+is%3Aclosed+label%3Abug))

  - type: textarea
    attributes:
      label: "Problem"
      description: "Describe the current behavior. May include logs, images, or videos."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Describe the steps you took to see the bug."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe the behavior you expect."
    validations:
      required: true

  - type: input
    attributes:
      label: "GCP-Tunneler version"
      placeholder: "0.0.1"
    validations:
      required: true
  - type: input
    attributes:
      label: "Operating system/version"
      placeholder: "macOS 11.5"
    validations:
      required: true
  - type: input
    attributes:
      label: "Terminal name/version"
      placeholder: "xterm 3.1"
    validations:
      required: true
  - type: input
    attributes:
      label: "$TERM environment variable"
      placeholder: "xterm-256color"
    validations:
      required: true
