on:
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        # go-version: stable
        go-version-file: ./go.mod
        cache: true

    - name: Get dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify
        
    # - name: Set up test environment
    #   run: |
    #     # Create a dummy .env file with test values
    #     echo "GCPT_SSH_TIMEOUT=12" > .env
    - name: Build
      run: go build ./...

    - name: Run tests
      run: go test ./...

    - name: Run linter
      uses: golangci/golangci-lint-action@v8
      # with:
      #   version: v2.1
