on:
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Get dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      env:
        GCPT_SSH_TIMEOUT: 12
      run: go test -v ./...

    - name: Run tests with race detection
      run: go test -race -v ./...

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
